### ISSUE TITLE
breaking change in 4.2.7 - AND and * operators do not work anymore

### ISSUE THREAD

**Issue by BGehrels** [RSeidelsohn/license-checker-rseidelsohn#94]
When i'm running
```
npx license-checker-rseidelsohn@4.2.6 --development --onlyAllow "MIT;WTFPL;BSD-3-Clause;BSD-2-Clause;Apache-2.0;ISC;0BSD;MPL;CC-BY-4.0;ODC-By-1.0;CC-BY-3.0;CC0-1.0;Python-2.0"
```
on my project - everything works fine.

But when i'm running
```
npx license-checker-rseidelsohn@4.2.7 --development --onlyAllow "MIT;WTFPL;BSD-3-Clause;BSD-2-Clause;Apache-2.0;ISC;0BSD;MPL;CC-BY-4.0;ODC-By-1.0;CC-BY-3.0;CC0-1.0;Python-2.0"
```
it shows

> Package "@swc/core-linux-x64-gnu@1.3.85" is licensed under "Apache-2.0 AND MIT" which is not permitted by the --onlyAllow flag. Exiting.

This is bad, because `Apache-2.0` as well as `MIT` are part of the whitelist.
I was able to reproduce the same for packages that are licensed as `MIT*`

**Comment by firecow** [comment]
Yeah, my renovate monday just went kapoom :smile:

**Comment by PeterMerkert** [comment]
Same here. Our entire CI is stopped now. The same problem occurs with OR operator.
We have fixed this temporarily by doing `npx license-checker-rseidelsohn@4.2.5 ...`

**Comment by RSeidelsohn** [comment]
Oh wow, thank you all and esp. @dvdmunckhof for the report! I'll hope to fix this ASAP. Shame on me.

**Comment by firecow** [comment]
I'm still getting this in 4.2.8

```
license-checker exclude_opt='--excludePackages @company/eslint-config-nodejs'
$ nodejs_shell npx license-checker-rseidelsohn --production --summary --excludePrivatePackages --onlyAllow "${NPM_LICENSE_CHECKER_ONLY_ALLOW_PRODUCTION}" ${exclude_opt}
├─ MIT: 33
├─ Python-2.0: 1
└─ ISC: 1
$ nodejs_shell npx license-checker-rseidelsohn --development --summary --excludePrivatePackages --onlyAllow "${NPM_LICENSE_CHECKER_ONLY_ALLOW_DEVELOPMENT}" ${exclude_opt}
Package "spdx-ranges@2.1.1" is licensed under "(MIT AND CC-BY-3.0)" which is not permitted by the --onlyAllow flag. Exiting.
```

`AND` and `OR` still doesn't seem to work.

**Comment by RSeidelsohn** [comment]
Hi folks, it took long, but I finally fixed the regression bug.
Due to the names the code used in the place I refactored for `v4.2.7`, I dangerously misinterpreted the meaning of the code.
While the code used the variable name `hasOnlyAllowedPackages`, what it _should_'ve used is `containsOneOfAllowedPackages` - I reverted my former refactoring and did it again, but this time in the right way.
It really is very important to choose good variable names.

Please check the latest version now - it should be good.

Thank you all for your reports, @BGehrels, @firecow, @PeterMerkert and @dvdmunckhof !

**Comment by dvdmunckhof** [comment]
@RSeidelsohn I can confirm the latest version is working as expected! Thanks for fixing it, much appreciated!

Have you considered using the [spdx-satisfies](https://www.npmjs.com/package/spdx-satisfies) package, which already is [a dependency](https://github.com/RSeidelsohn/license-checker-rseidelsohn/blob/9c0099d87d71e4eb82972e07461bb026d3da643f/package.json#L139) of this project? It could handle the license matching for you, in an even more robust way. Because the current approach does not handle all cases correctly, as mentioned in [my previous comment](https://github.com/RSeidelsohn/license-checker-rseidelsohn/issues/94#issuecomment-1723065464).

**Comment by RSeidelsohn** [comment]
Hello Dennis,

thank you for that suggestion! I'll look into this. So far, this part of the code is still kind of a black box to me - definitely something I should gain a thorough understanding of.

Currently, I'm fixing a bug with --depth I was pointed to - while waiting in a café for my son to finish his swimming course... so you see, time is still a limiting factor for me.

Your idea is very good, though.

Cheers and thanks for the response!
Roman

Am 13. Oktober 2023 16:08:49 MESZ schrieb Dennis van den Munckhof ***@***.***>:
